//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bazarEntities : DbContext
    {
        public bazarEntities()
            : base("name=bazarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcategory> tblcategories { get; set; }
        public virtual DbSet<tblcity> tblcities { get; set; }
        public virtual DbSet<tblmarket> tblmarkets { get; set; }
        public virtual DbSet<tblproduct> tblproducts { get; set; }
        public virtual DbSet<tblrole> tblroles { get; set; }
        public virtual DbSet<tblshoe> tblshoes { get; set; }
        public virtual DbSet<tblshoptype> tblshoptypes { get; set; }
        public virtual DbSet<tblsizechartname> tblsizechartnames { get; set; }
        public virtual DbSet<tblfemaleGarment> tblfemaleGarments { get; set; }
        public virtual DbSet<tblmaleGarment> tblmaleGarments { get; set; }
        public virtual DbSet<tblcreateUser> tblcreateUsers { get; set; }
        public virtual DbSet<tblsizePantFemale> tblsizePantFemales { get; set; }
        public virtual DbSet<tblsizePantMale> tblsizePantMales { get; set; }
        public virtual DbSet<tblsizeShirtFemale> tblsizeShirtFemales { get; set; }
        public virtual DbSet<tblsizeShirtMale> tblsizeShirtMales { get; set; }
        public virtual DbSet<tblsizeSho> tblsizeShoes { get; set; }
        public virtual DbSet<tblcustomerOrder> tblcustomerOrders { get; set; }
    
        public virtual ObjectResult<serachFemaleGarment_Result> serachFemaleGarment(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<serachFemaleGarment_Result>("serachFemaleGarment", searchParameter);
        }
    
        public virtual ObjectResult<serachMaleGarment_Result> serachMaleGarment(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<serachMaleGarment_Result>("serachMaleGarment", searchParameter);
        }
    
        public virtual ObjectResult<serachShoes_Result> serachShoes(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<serachShoes_Result>("serachShoes", searchParameter);
        }
    }
}
