//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomerOrder
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> counts { get; set; }
        public string addresss { get; set; }
        public string cityname { get; set; }
        public string size { get; set; }
        public string mobileNo { get; set; }
        public string Email { get; set; }
        public string status { get; set; }
        public string reviews { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> ownerId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
