//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmaleGarment
    {
        public int id { get; set; }
        public string clothname { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string shirtsizechartid { get; set; }
        public string pantsizechartid { get; set; }
        public Nullable<bool> xsmall { get; set; }
        public Nullable<bool> small { get; set; }
        public Nullable<bool> medium { get; set; }
        public Nullable<bool> large { get; set; }
        public Nullable<bool> xlarge { get; set; }
        public Nullable<bool> xxlarge { get; set; }
        public string pic1 { get; set; }
        public string pic2 { get; set; }
        public string detail { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> createdById { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
